site_name: SYANiDE-.github.io writeups
site_url: https://syanide-.github.io/writeups/

theme:
    name: 'material'
    features:
      - navigation.instant
      - navigation.instant.progress
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.expand
      - navigation.path
      - navigation.prune
      - navigation.indexes
      - toc.follow
      - toc.integrate
      - navigation.top
      - header.autohide
      - search.highlight
      - search.share

    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - glightbox:
      closeEffect: zoom
      openEffect: zoom
      closebutton: show
      closeOnOutsideClick: true
      descPosition: top
      touchNavigation: false
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - asciinema-player
  - panzoom:
      always_show_hint: true # default false
      key: "alt" # default alt

      

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
  - javascripts/app.js

extra_css:
  - css/app.css

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/SYANiDE-
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chasejhatch/
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/298244420195844096